### ISSUE TITLE
Add more details about compute resources to schema

### ISSUE THREAD

**Issue by max-radin** [isi-usc-edu/qb-gsee-benchmark#12]
The schema should have (optional) fields for details about compute hardware such as number of CPUs, number of logical qubits, number of T gates, etc. This should include both aggregates at the problem-instance level (e.g. max number of logical qubits) as well as resources for an individual Hamiltonian.

We should also make the runtime field optional for resource estimates so that performers can report estimated logical compute resources without modeling the hardware itself.

**Comment by jp7745** [comment]
include `solver_uuid` field.

**Comment by jtcantin** [comment]
Closing this as resolved.
