### ISSUE TITLE
Logical QRE script and solution files

### ISSUE THREAD

**Issue by max-radin** [isi-usc-edu/qb-gsee-benchmark#13]
We should add solution files representing pyLIQTR logical QREs for a number of the problem instances, as well as a script that generates these.

For now we can use some nominal values for the overlaps and truncation threshold. Such parameters should be configurable so that we can scan/change them later. They should also be recorded in the solution file.

**Comment by jp7745** [comment]
see `scripts/calculate_all_LREs_script.py` as a starting point.
