### ISSUE TITLE
planted_solution JSON fix 

### ISSUE THREAD

**Issue by jp7745** [isi-usc-edu/qb-gsee-benchmark#16]
We are currently not enforcing this in the schema, so it slipped through until now.  

Please integrate `requirements` and `features` into the list of `instance_data`. 
For example:

```JSON
"instance_data":[
    {
        "supporting_files": ... 
        "requirements": { }  # one object, not a list.
        "features": {}  # one object, not a list.
    }
]
```

**Comment by jtcantin** [comment]
Addressed in jtcantin-problem_instance_updates branch, commit eb8dc1905ea171ebbad00e7e2474f3feb342829f
