### ISSUE TITLE
6/8 catalysis instances

### ISSUE THREAD

**Issue by jp7745** [isi-usc-edu/qb-gsee-benchmark#7]
track down the missing 2 catalysis JSON instances and verify corresponding FCIDUMP files are in the SFTP server.

**Comment by bellonzi** [comment]
To-do: 
- Specify problem instances missing (fe_red and [xxx])
- Ensure that associated hamiltonians are on sftp server
- Upload old json files

**Comment by jp7745** [comment]
are they in the old Zapata git history?

**Comment by bellonzi** [comment]
Okay, those are the missing ones. I'll investigate why they aren't passing. I also downloaded the old ones from your deprecated problem instances repo because that's the last time I had seen them.

**Comment by aakunitsa** [comment]
@bellonzi  I have "old" jsons for fe_red and ru_macho. I can send them to you.

**Comment by bellonzi** [comment]
No worries @aakunitsa - I've already cleaned up the jsons in [https://github.com/isi-usc-edu/qb-gsee-benchmark/tree/7-68-catalysis-instances](qb-gsee-benchmark/tree/7-68-catalysis-instances). I just need to check the sftp server and I'll PR into main

**Comment by jtcantin** [comment]
These catalyst problem instances have been updated to the latest schema and incorporated into branch `jtcantin-problem_instance_updates` at commit `891e08891096a25b0e817f01a0b0c792af95b4a4`. Closed related pull request.

@bellonzi Just to confirm, are the Hamiltonians on the sftp server?

**Comment by bellonzi** [comment]
Yes, they are and your copies of [fe_red](https://github.com/isi-usc-edu/qb-gsee-benchmark/blob/jtcantin-problem_instance_updates/problem_instances/problem_instance.fe_red.a8895776-3583-4884-fbc7-d6f9df21a7ac.json) and [ru_macho](https://github.com/isi-usc-edu/qb-gsee-benchmark/blob/jtcantin-problem_instance_updates/problem_instances/problem_instance.ru_macho.b78a10f2-ce8a-43c0-69ec-4cf666d8e85c.json) have the correct addresses.
